include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "build/**"
    - "lib/generated/**"
  errors:
    # 警告を無視する設定
    prefer_const_constructors: ignore
    prefer_const_literals_to_create_immutables: ignore
    use_key_in_widget_constructors: ignore

linter:
  rules:
    # 必要に応じてここに厳しいルールを追加できるけど、今は無しでいくわよ！